"""add external_id

Revision ID: 1a33c4011143
Revises: 957051a07a32
Create Date: 2026-04-03 12:37:01.294034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a33c4011143'
down_revision: Union[str, Sequence[str], None] = '957051a07a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_column('matches', 'external_id')
    # ### end Alembic commands ###
